import {setGlobalOptions} from "firebase-functions";
setGlobalOptions({ maxInstances: 10 });
export {transcribeDocument} from "./transcribe-document";
export {transcribeAudio} from "./transcribe-audio";
export {transcribeImages} from "./transcribe-images";
export {savorDocument} from "./savor-document";
export {generateMeanings} from "./generate-meanings";
export {generateResponse} from "./generate-response";
export {cascadeDeleteRoom} from "./cascade-delete-room";
export {deleteAccount} from "./delete-account";
export {deleteUnusedWordlists} from "./delete-unused-wordlists";
export {createUserdata} from "./create-userdata";
export {textToSpeech} from "./text-to-speech";
export {createDailyTasks, createWordLists} from "./create-daily-tasks";
export {appleServerNotifications} from "./apple-server-notifications";
export {syncRevenueCatSubscription} from "./sync-revenuecat-subscription";
export {updateUserPlans} from "./update-user-plans";
export {addMonthlyFreeGems} from "./add-monthly-free-gems";
export {addGems} from "./add-gems";
export {sendPushNotification, sendNotificationManual, sendBulkNotification} from "./send-notification";
export {saveFCMToken} from "./save-fcm-token";
export {transcribeVideo} from "./transcribe-video";
export {sendDailyNotification, sendWordListReminder, sendReviewReminder} from "./daily-notification";
